### ndarray的索引(index), 切割(slice)

In [1]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]


array([7, 8, 9])

In [5]:
import  random
random.randint(50, 100)  # 在50與99之間隨機取一個數字

65

In [16]:
np.random.randint(50, 101 ,size = 5)
scores = np.random.randint(50, 101 ,size = (50,5))
scores

array([[ 90,  99,  74,  80,  93],
       [ 81,  78,  91,  54,  70],
       [ 63,  63,  94,  64,  59],
       [ 59,  65,  70,  60,  84],
       [ 96,  52,  64,  62,  54],
       [ 88,  84,  78,  84,  97],
       [ 57,  86,  55,  73,  73],
       [ 99, 100,  62,  91,  83],
       [ 75,  59,  85,  77,  56],
       [ 71,  86,  95,  56,  71],
       [ 67,  93,  61,  54,  88],
       [ 67,  75,  53,  54,  63],
       [ 67,  70,  87,  87,  91],
       [ 67,  67,  78,  68,  76],
       [ 98,  71,  67,  94,  54],
       [ 55,  68,  61,  75,  63],
       [ 92,  67,  92,  63,  71],
       [ 93,  96,  63,  91, 100],
       [ 50,  76,  57,  58,  70],
       [ 66,  97,  92,  79,  78],
       [ 79,  91,  92,  67,  63],
       [ 93,  57,  73,  71,  58],
       [ 68,  82,  75,  67,  52],
       [ 70,  76,  92,  66,  83],
       [ 77,  75,  56,  57,  58],
       [ 67,  84,  51,  97,  79],
       [ 94,  53,  72,  81,  95],
       [ 81,  63,  79,  83,  92],
       [ 96,  84,  77,  65,  80],
       [ 68,  

In [10]:
np.random.randint(50, 101 ,size = 5)
scores = np.random.randint(50, 101 ,size = (50,5))
scores.size
scores.shape

(50, 5)

In [18]:
scores[:,0]
scores[:,0:1]

array([[ 69],
       [ 78],
       [ 94],
       [ 96],
       [ 89],
       [ 74],
       [ 91],
       [ 59],
       [ 57],
       [ 88],
       [ 84],
       [ 70],
       [ 85],
       [ 91],
       [ 71],
       [ 68],
       [ 71],
       [ 62],
       [ 60],
       [ 90],
       [ 70],
       [ 89],
       [ 98],
       [ 53],
       [100],
       [ 63],
       [ 69],
       [ 95],
       [ 71],
       [ 55],
       [ 82],
       [ 84],
       [ 65],
       [ 87],
       [ 88],
       [ 60],
       [ 85],
       [ 65],
       [ 90],
       [ 89],
       [ 63],
       [ 61],
       [ 62],
       [ 80],
       [ 97],
       [ 53],
       [ 62],
       [ 59],
       [ 63],
       [ 64]], dtype=int32)

In [17]:
scores[0,:]
scores[0:1,:]

array([[90, 99, 74, 80, 93]], dtype=int32)

In [20]:
np.sum(scores,axis=1)  #計算每一位的總分

array([358, 367, 447, 376, 400, 355, 427, 327, 346, 433, 399, 328, 363,
       370, 398, 365, 361, 415, 367, 382, 350, 428, 403, 362, 400, 344,
       333, 403, 375, 305, 362, 373, 367, 382, 419, 373, 350, 410, 383,
       384, 372, 421, 377, 402, 409, 379, 355, 378, 349, 355])

In [ ]:
np.mean(scores, axis=1) #計算每一位的平均

array([71.6, 73.4, 89.4, 75.2, 80. , 71. , 85.4, 65.4, 69.2, 86.6, 79.8,
       65.6, 72.6, 74. , 79.6, 73. , 72.2, 83. , 73.4, 76.4, 70. , 85.6,
       80.6, 72.4, 80. , 68.8, 66.6, 80.6, 75. , 61. , 72.4, 74.6, 73.4,
       76.4, 83.8, 74.6, 70. , 82. , 76.6, 76.8, 74.4, 84.2, 75.4, 80.4,
       81.8, 75.8, 71. , 75.6, 69.8, 71. ])

In [28]:
arr = np.random.randn(5)
arr

array([-0.85981412, -0.49025324,  0.09380945,  1.4604589 ,  0.48962235])

In [ ]:
# 使用比較運算子
arr = np.random.randn(5)
arr > 0

array([False,  True, False, False,  True])

In [ ]:
np.where(arr > 0, 1,0)  #如果是true就傳1, false就傳0

array([0, 1, 0, 0, 1])

In [ ]:
np.where(arr > 0, 1, arr)  #如果是true就傳1, false就傳出arr數值數值

array([-1.04030664,  1.        , -1.69553428, -0.61500915,  1.        ])