https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [3]:
import numpy as np
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros((3, 4)) #裡面包了一個tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(0, 1, 0.1)  #建立0~1之間，每增加一個數字就+0.1，其中不包含1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.linspace(0, 1, 10)  #建立0~1之間，共有10筆數據，其中不包含1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.random.rand(3, 4)

array([[0.33954391, 0.25637271, 0.65233277, 0.52551613],
       [0.31121517, 0.77391135, 0.91137638, 0.86157276],
       [0.5841693 , 0.99946282, 0.6203923 , 0.46305711]])

In [8]:
scores = np.random.randint(50,101,size=(50, 5))  # 50~100之間隨機出現，其中以size來規範共50個學生，每個學生共產生5筆數據
scores

array([[ 51,  55,  58,  63,  58],
       [ 83,  81,  73,  61,  77],
       [ 55,  95,  84,  55,  89],
       [ 51,  91,  69,  77,  78],
       [ 52,  58,  82,  78,  85],
       [ 55,  99,  62,  65,  58],
       [ 56,  63,  62,  81,  75],
       [ 90,  52,  80,  90,  72],
       [ 99,  58,  90,  83,  92],
       [ 51,  81,  63,  71,  73],
       [ 78, 100,  97,  98,  75],
       [ 55,  70,  64,  66,  87],
       [ 78,  97,  79,  84,  53],
       [ 93,  89,  74,  57,  89],
       [ 80,  68,  62,  55,  73],
       [ 88,  67,  52,  73,  86],
       [ 86,  64,  96,  96,  95],
       [ 53,  79,  67,  92,  98],
       [ 81,  92,  76,  77,  98],
       [ 73,  55,  86,  76,  93],
       [ 83,  67,  54,  97,  84],
       [ 55, 100,  63,  74,  97],
       [ 65,  50,  86,  90,  63],
       [ 82,  95,  69,  81,  60],
       [ 70,  84,  91,  53,  88],
       [ 75,  84,  81,  65,  75],
       [ 84,  78,  54,  53,  68],
       [ 94,  51,  81,  95,  78],
       [ 96,  60,  58,  58,  91],
       [ 59,  