https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

In [1]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[61, 98, 61, 63, 62],
       [62, 87, 88, 76, 91],
       [60, 70, 69, 72, 92],
       [89, 60, 88, 77, 64],
       [58, 50, 61, 57, 79]], dtype=int32)

In [ ]:
scores[:3,2:]   # [:3 , 2:] 的意思是縱軸從1抓到3，橫軸從第2個開始算後面全要(橫軸是從0開始算起)，就是抓右上角的矩陣

array([[61, 63, 62],
       [88, 76, 91],
       [69, 72, 92]], dtype=int32)

In [6]:
scores[4]

array([98, 51, 99, 89, 85], dtype=int32)

In [7]:
scores[4,:]

array([98, 51, 99, 89, 85], dtype=int32)

In [11]:
scores[4:,:]

array([[98, 51, 99, 89, 85]], dtype=int32)

In [12]:
scores[:,:2]

array([[ 70,  83],
       [ 79, 100],
       [ 77,  52],
       [ 82,  76],
       [ 98,  51]], dtype=int32)

### numpy的統計工具

In [15]:
scores = np.random.randint(50, 101, size=(5, 5))
scores

array([[ 94,  93,  87,  64,  92],
       [ 64,  54,  80,  62,  84],
       [ 60,  60, 100,  82,  78],
       [ 78,  79,  71,  59,  62],
       [ 69,  77,  82,  71,  83]], dtype=int32)

In [16]:
scores[:,0] +scores[:,1] +scores[:,2] +scores[:,3] + scores[:,4]

array([430, 344, 380, 349, 382], dtype=int32)

In [ ]:
#加總
np.sum(scores, axis=1)  #答案與上述相同

array([430, 344, 380, 349, 382])

In [19]:
#平均
np.mean(scores, axis=1)

array([86. , 68.8, 76. , 69.8, 76.4])

In [24]:
#最大
np.max(scores,axis=1)

array([ 94,  84, 100,  79,  83], dtype=int32)

In [21]:
#最小
np.min(scores, axis=1)

array([64, 54, 60, 59, 69], dtype=int32)

In [22]:
#中間數
np.median(scores, axis=1)

array([92., 64., 78., 71., 77.])

In [23]:
#標準差
np.std(scores, axis=1)

array([11.26055061, 11.35605565, 15.01998668,  8.13387976,  5.64269439])