https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [2]:
import numpy as np
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros((3, 4)) #裡面包了一個tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.random.rand(3, 4)

array([[0.33954391, 0.25637271, 0.65233277, 0.52551613],
       [0.31121517, 0.77391135, 0.91137638, 0.86157276],
       [0.5841693 , 0.99946282, 0.6203923 , 0.46305711]])

In [18]:
scores = np.random.randint(50,101,size=(50, 5))
scores

array([[ 71,  57,  61,  74,  66],
       [ 76,  95,  94,  52,  91],
       [ 60,  57,  90,  73,  58],
       [ 97,  76,  75,  56,  83],
       [ 71,  81,  79,  56,  65],
       [ 66,  53,  97,  98,  75],
       [ 61,  50,  55,  89,  86],
       [ 65,  52,  67,  60,  72],
       [100,  95,  67,  67,  99],
       [ 78,  51,  84,  96, 100],
       [ 83,  79,  85,  68,  61],
       [ 91,  74,  90,  82,  63],
       [ 99,  77,  50,  97,  96],
       [ 67,  97,  52,  70,  54],
       [ 98,  95,  61,  89,  79],
       [ 75,  82,  64,  66,  71],
       [ 52,  90,  75,  54,  99],
       [ 51,  97,  69,  81,  66],
       [ 62,  52,  80,  84,  74],
       [ 81,  80,  82,  90,  50],
       [ 90,  87,  67,  98,  74],
       [ 82,  95,  87,  84,  53],
       [ 85,  70,  95,  86,  96],
       [ 92,  90,  76,  65,  90],
       [ 91,  65,  81,  66,  56],
       [ 85,  66,  74,  81,  82],
       [100,  95,  54,  87,  77],
       [ 92,  80,  64,  97,  82],
       [ 94,  89,  59,  58,  99],
       [ 56,  